"""initial schema

Revision ID: 15528104623c
Revises: 
Create Date: 2026-08-05 11:07:35.076271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '15528104623c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector 扩展（PostgreSQL 16，定案）
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('job_title', sa.String(length=128), nullable=False),
    sa.Column('salary_p25', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_p50', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_p75', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('trend', sa.String(length=16), nullable=True),
    sa.Column('heat', sa.String(length=16), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('data_source', sa.String(length=256), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_data_city_industry_job', 'market_data', ['city', 'industry', 'job_title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('task_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stage', sa.String(length=128), nullable=True),
    sa.Column('result_ref', sa.String(length=512), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_jobs_status'), 'task_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_task_jobs_task_type'), 'task_jobs', ['task_type'], unique=False)
    op.create_index(op.f('ix_task_jobs_user_id'), 'task_jobs', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('school', sa.String(length=128), nullable=True),
    sa.Column('major', sa.String(length=128), nullable=True),
    sa.Column('education', sa.String(length=32), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('internships', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('certificates', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('career_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('stage', sa.String(length=20), server_default='stage1', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_reports_status'), 'career_reports', ['status'], unique=False)
    op.create_index(op.f('ix_career_reports_user_id'), 'career_reports', ['user_id'], unique=False)
    op.create_table('career_directions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=128), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('salary_p25', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_p50', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_p75', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('trend', sa.String(length=16), nullable=True),
    sa.Column('heat', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['career_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_directions_report_id'), 'career_directions', ['report_id'], unique=False)
    op.create_table('gap_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('direction_id', sa.UUID(), nullable=True),
    sa.Column('target_job', sa.String(length=128), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['career_directions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['career_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_analyses_report_id'), 'gap_analyses', ['report_id'], unique=False)
    op.create_table('growth_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('gap_analysis_id', sa.UUID(), nullable=True),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gap_analysis_id'], ['gap_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['career_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_plans_report_id'), 'growth_plans', ['report_id'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('resource', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='todo', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['growth_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_tasks_plan_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_index(op.f('ix_growth_plans_report_id'), table_name='growth_plans')
    op.drop_table('growth_plans')
    op.drop_index(op.f('ix_gap_analyses_report_id'), table_name='gap_analyses')
    op.drop_table('gap_analyses')
    op.drop_index(op.f('ix_career_directions_report_id'), table_name='career_directions')
    op.drop_table('career_directions')
    op.drop_index(op.f('ix_career_reports_user_id'), table_name='career_reports')
    op.drop_index(op.f('ix_career_reports_status'), table_name='career_reports')
    op.drop_table('career_reports')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_task_jobs_user_id'), table_name='task_jobs')
    op.drop_index(op.f('ix_task_jobs_task_type'), table_name='task_jobs')
    op.drop_index(op.f('ix_task_jobs_status'), table_name='task_jobs')
    op.drop_table('task_jobs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_market_data_city_industry_job', table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###